# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - ./scripts/replace-env-vars.sh

builds:
  - builder: deno
    targets:
      - x86_64-pc-windows-msvc
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    #
    # Default: Project directory name.
    binary: pylee
    
    # Main entry point.
    #
    # Default: 'main.ts'.
    main: "src/bin/cli.ts"
  
    # Custom flags.
    #
    # Templates: allowed.
    # Default: [].
    flags:
      - --allow-env
      - --allow-net
      - --allow-run
      - --allow-sys
      - --allow-read
      - --allow-write
      - --node-modules-dir
      - --unstable-sloppy-imports
      - --include
      - package.json
      - --include
      - src/html
      

      
npms:
  # Package name.
  #
  # Required
  - name: "@pyleeai/pylee"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"



release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

after:
  hooks:
    - ./scripts/restore-env-file.sh
