# .github/workflows/release.yml
name: release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: deno install
      - name: npm login
        run: |
          npm config set '//registry.npmjs.org/:_authToken'=${{ secrets.NPM_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser-pro
          # 'latest', 'nightly', or a semver
          version: nightly
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          PYLEE_OIDC_AUTHORITY: ${{ secrets.PYLEE_OIDC_AUTHORITY }}
          PYLEE_OIDC_CLIENT_ID: ${{ secrets.PYLEE_OIDC_CLIENT_ID }}
          PYLEE_OIDC_REDIRECT_URI: ${{ vars.PYLEE_OIDC_REDIRECT_URI }}
          PYLEE_OIDC_PORT: ${{ vars.PYLEE_OIDC_PORT }}
